store:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/store
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: lSDH8ZPQWQG6s2P0GXzG6acyYC56JbUD
            scope:
              - openid
              - view_catalogue